#
# Makefile for APM X-GENE Ethernet driver.
#

xgene-enet-objs := \
		xgene_enet_common.o	\
		xgene_enet_mac.o	\
		xgene_enet_main.o	\
		xgene_enet_err.o	\
		xgene_enet_tools.o

obj-$(CONFIG_NET_XGENE) += xgene-enet.o
