#!/bin/bash

. debian/debian.env

# We have to be in the top level kernel source directory
if [ ! -f MAINTAINERS ] || [ ! -f Makefile ]; then
	echo "This does not appear to be the kernel source directory." 1>&2
	exit 1
fi

. ${DEBIAN}/etc/kernelconfig

ARCH=$(echo $archs | tr " " "\n" | sort -u)
FLAVOUR=$(for arch in ${ARCH}; do
	flavours=$(sed -ne 's/^flavours\s*=\s*\(.*\)$/\1/p' ${DEBIAN}/rules.d/${arch}.mk)
	for flavour in ${flavours}; do
		echo ${arch}-${flavour}
	done
done | tr " " "\n" | sort -u)

while read line; do
	(echo $line | grep -q '^#') || break
done

cat << EOF
# Menu: HEADER
# FORMAT: 4
# ARCH: $(echo ${ARCH})
# FLAVOUR: $(echo ${FLAVOUR})

EOF

while read line; do
	echo ${line}
done
