#!/bin/bash
full_version=`uname -r`

# First check for a fully qualified version.
this="/usr/lib/linux-tools/$full_version/`basename $0`"
if [ -f "$this" ]; then
	exec "$this" "$@"
fi

# Removing flavour from version i.e. generic or server.
flavour_abi=${full_version#*-}
flavour=${flavour_abi#*-}
version=${full_version%-$flavour}
this="$0_$version"
if [ -f "$this" ]; then
	exec "$this" "$@"
fi

# Give them a hint as to what to install.
echo "`basename $0` not found for kernel $version" >&2
if dpkg --compare-versions "$full_version" lt "3.11.0"; then
	flavour=''
else
	flavour="-$flavour"
fi
echo "You may need to install linux-tools-$version$flavour for this kernel." >&2
echo "You may also wish to install linux-tools$flavour or" >&2
echo "linux-image$flavour-lts-<series> to keep up to date." >&2
exit 2
