#!/bin/bash
full_version=`uname -r`

# Removing flavour from version i.e. generic or server.
flavour_abi=${full_version#*-}
flavour=${flavour_abi#*-}
version=${full_version%-$flavour}
x86_energy_perf_policy="x86_energy_perf_policy_$version"

if ! which "$x86_energy_perf_policy" > /dev/null; then
    echo "$x86_energy_perf_policy not found" >&2
    echo "You may need to install linux-tools-$version" >&2
    exit 2
fi

exec "$x86_energy_perf_policy" "$@"
