vendor_btcoexist-objs :=halbtc8192e2ant.o	\
			halbtc8723b1ant.o	\
			halbtc8723b2ant.o	\
			halbtc8821a1ant.o	\
			halbtc8821a2ant.o	\
			halbtc8822b1ant.o	\
			halbtc8822b2ant.o	\
			halbtc8822bwifionly.o	\
			halbtcoutsrc.o		\
			rtl_btc.o

obj-$(CONFIG_RTL_VENDOR_BTCOEXIST) += vendor_btcoexist.o

ccflags-y += -D__CHECK_ENDIAN__
