# SPDX-License-Identifier: GPL-2.0-only
adv7511_drm-y := adv7511_drv.o adv7533.o
adv7511_drm-$(CONFIG_DRM_I2C_ADV7511_AUDIO) += adv7511_audio.o
adv7511_drm-$(CONFIG_DRM_I2C_ADV7511_CEC) += adv7511_cec.o
obj-$(CONFIG_DRM_I2C_ADV7511) += adv7511_drm.o
