obj-$(CONFIG_RTLWIFI_VENDOR) 	+= rtlwifi_vendor.o
rtlwifi_vendor-objs	:=		\
		base.o		\
		cam.o		\
		core.o		\
		debug.o		\
		efuse.o		\
		ps.o		\
		rc.o		\
		regd.o		\
		stats.o

obj-$(CONFIG_RTLWIFI_VENDOR_PCI)	+= rtl_vendor_pci.o
rtl_vendor_pci-objs	:=		pci.o

obj-$(CONFIG_RTLWIFI_VENDOR_USB)	+= rtl_vendor_usb.o
rtl_vendor_usb-objs	:=		usb.o

obj-$(CONFIG_RTL_VENDOR_BTCOEXIST)	+= btcoexist/
obj-$(CONFIG_RTLHALMAC)		+= halmac/
obj-$(CONFIG_RTLPHYDM)		+= phydm/
obj-$(CONFIG_RTL8822BE)		+= rtl8822be/
