

halmac-objs := \
	halmac_api.o	\
	halmac_88xx/halmac_api_88xx_usb.o	\
	halmac_88xx/halmac_api_88xx_sdio.o	\
	halmac_88xx/halmac_api_88xx.o	\
	halmac_88xx/halmac_api_88xx_pcie.o	\
	halmac_88xx/halmac_func_88xx.o	\
	halmac_88xx/halmac_8822b/halmac_api_8822b_pcie.o	\
	halmac_88xx/halmac_8822b/halmac_func_8822b.o	\
	halmac_88xx/halmac_8822b/halmac_api_8822b_sdio.o	\
	halmac_88xx/halmac_8822b/halmac_api_8822b.o	\
	halmac_88xx/halmac_8822b/halmac_8822b_phy.o	\
	halmac_88xx/halmac_8822b/halmac_8822b_pwr_seq.o	\
	halmac_88xx/halmac_8822b/halmac_api_8822b_usb.o	\
	rtl_halmac.o


obj-m = halmac.o
