#!/bin/sh

path_prefix=$1
dtb_its=$2

echo "Make FDT its file ..."

echo "/*
 * Simple DTB source files contained in a single U-Boot FIT image
 */

/dts-v1/;

/{
	description = \"Device Tree List\";
	#address-cells = <1>;

	images {" > $dtb_its

find ${path_prefix} -name *.dtb -printf "%P\n" | while read line; do
	dtb_file_name=$line
	dtb_name=`echo $dtb_file_name | sed -e "s/\//_/g"`
	echo "		"$dtb_name" {
			description = \"$dtb_name\";
			data = /incbin/(\"$path_prefix/$dtb_file_name\");
			type = \"flat_dt\";
			arch = \"arm64\";
			compression = \"none\";
		};
" >> $dtb_its
done

echo "	};
};" >> $dtb_its
